### ISSUE TITLE
Doesn't change anything

### ISSUE THREAD

**Issue by mctrivia** [agilord/diacritic#3]
I don't know if it is me but when I do 

    print(removeDiacritics('évaluer'));

I get évaluer printed.  Same is also true of every other word on my word list.

**Comment by isoos** [comment]
Interesting: I've copy-pasted your `é` and it is definitely different from my `é`. Could you please copy-paste all the accented characters that the library was not able to remove? It seems an update of the mapping file is due...

**Comment by mctrivia** [comment]
https://github.com/mctrivia/bip39-1/tree/master/lib/src/wordlists

**Comment by isoos** [comment]
Hm, interesting: these are combined unicode characters, e.g. `0x0061 0x0301`, or `0x006e 0x0303`. It seems that `0x0301` and `0x0303` is part of the unicode combining diacritical marks, which could be removed when present:
https://www.fileformat.info/info/unicode/block/combining_diacritical_marks/index.htm

This should be fixed soon.

**Comment by isoos** [comment]
Fix is published in `0.1.1`.

**Comment by mctrivia** [comment]
thank you.  Have not gone through complete list but seems to be working.
