### ISSUE TITLE
can we have the java version of this library?

### ISSUE THREAD

**Issue by deepak786** [agilord/diacritic#4]

**Comment by isoos** [comment]
@deepak786: you are free to port it :)
However, as it happens, it is easy to do this in java: https://www.drillio.com/en/2011/java-remove-accent-diacritic/

**Comment by deepak786** [comment]
I already tried but the issue is:

your library: diacritics
converts the ß to s 

but using the normalize function from normalizer doesn't convert ß to s. It still gives ß.
Do you know how can I have this using normalizer?

**Comment by isoos** [comment]
Use simple String replacement calls? I imagine there may be only a few of these characters...

**Comment by deepak786** [comment]
You also managed in the same way in your library diacritics?

**Comment by isoos** [comment]
This library is a bit inferior to the Java normalizer, as it uses mostly the replacements, see: https://github.com/agilord/diacritic/blob/master/lib/src/replacement_map.dart

**Comment by deepak786** [comment]
@isoos I'm trying to convert this library into a java version.
1. \xDF replaced with ss. But in the library, there is also \u00DF which is replaced with s.
2. \x6E\xF1 replaced with n.

I want to confirm the following points:
1. Are \xDF and \u00DF the same?
2. Are \x6E and \u006E the same?
3. Are \xF1 and \u00F1 the same?

if yes then why you have used both unicodes?

reference for \x6E and \u006E, https://www.toptal.com/designers/htmlarrows/letters/lowercase-n/


could you please help me to understand the above points?

**Comment by deepak786** [comment]
Java Version of this library:
https://github.com/deepak786/diacritic
